### ISSUE TITLE
Genomics of Drug Sensitivity

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/oncoEnrichR#1]
Hi @sigven and happy new year!

Is there a thought to also add drug sensitivity data in this tool?

Like:
https://www.cancerrxgene.org/

**Comment by sigven** [comment]
Hi @kokyriakidis,
Happy new years to you too! I have not thought about this yet, do you have any specific suggestion as to how it may be utilized to rank/prioritize genesets?
best,
Sigve

**Comment by kokyriakidis** [comment]
Hi @sigven ,

I had a second look at this resource and I realized that they only have data regarding the relationship of a muteted gene and the sensitivity of several drugs. So maybe it is more appropriate for pcgr.

**Comment by sigven** [comment]
Hi @kokyriakidis,

Yeah, I believe you are right. I have plans to include this resource in PCGR, with the overall aim of showing: 
a ) the model system(s) (cell lines) that are mostly resembling the tumor that is analyzed, and
b ) how the cell line(s) respond to various antineoplastic agents (i.e. the actual drug sensitivity data)
The essential challenge is how to accomplish a) in a robust manner. I am aware of some other efforts that might be relevant, in particular the [CELLector package](https://github.com/francescojm/CELLector). Thanks for your interest:-)
