### ISSUE TITLE
conditions failed for call

### ISSUE THREAD

**Issue by antoine4ucsd** [sigven/oncoEnrichR#25]
Hello
I've installed your nice package on my Mac (no issue)
I am submitting a list of 430 genes with the following commands:
```
oeDB <- oncoEnrichR::load_db(cache_dir = "mydir/")
land_df_wide_informed=land_df_wide3%>%dplyr::filter(!is.na(SYMBOL))
dim(land_df_wide_informed)
myc_report <- oncoEnrichR::onco_enrich(query = mydata$SYMBOL, oeDB = oeDB, show_cell_tissue = T, project_title = "my title", project_owner = "myself")
```
I get this error suggesting that the gene symbols is not correct but I have no issue when uploading on public database such as NCI or CCGD. 

Error: conditions failed for call 'oncoEnrichR::onco_enrich(query = land_df_wide_informed[1:10, ':
	 * !is.null(.) && (is(., "GeneSet")) && !is.null(geneIds(.))
 Description: Please enter correct inputGenes.
                    It should be a Gene set object.

this error does not occur with the online version of oncoenrich.
thank you!

**Comment by sigven** [comment]
Hi @antoine4ucsd,  

Thanks for using oncoEnrichR! Just a quick question: did you remember to run library(oncoEnrichR) before you started your analysis? 

Best, 
Sigve

**Comment by antoine4ucsd** [comment]
Yes I did
it starts properly but failed after a few seconds

**Comment by sigven** [comment]
Ok, got it. In order for me to reproduce the error and figure out what is going wrong, I need:
- your query list of 430 genes (if you do not want to share here, you can e-mail me (sigven AT ifi.uio.no)

It would also be great if you can show the output of `sessinInfo()` from your R console.

PS: The R commands shown above are not completely coherent. E.g. `mydata$SYMBOL`, which you feed in as the value to the `query` argument is not defined. Also, not really sure what `land_df_wide_informed` is used for?

**Comment by antoine4ucsd** [comment]
sent
thank you!
